spring:
  redis:
    #host: 10.10.94.154
    #port: 6379
    password:
    cluster:
      nodes: dev81:6379,dev82:6379,dev83:6379,dev81:6380,dev82:6380,dev83:6380
    database: 0
    pool:
      max-active: 8
      max-wait: 1
      max-idle: 8
      min-idle: 0
    timeout: 10000


